In [53]:
from math import sqrt

In [54]:
critics = {
'레드벨벳': {
'택시운전사': 2.5,
'겨울왕국': 3.5,
'리빙라스베가스': 3.0,
'넘버3': 3.5,
'사랑과전쟁': 2.5,
'세계대전': 3.0,
},
'BTS': {
'택시운전사': 1.0,
'겨울왕국': 4.5,
'리빙라스베가스': 0.5,
'넘버3': 1.5,
'사랑과전쟁': 4.5,
'세계대전': 5.0,
},
'블랙핑크': {
'택시운전사': 3.0,
'겨울왕국': 3.5,
'리빙라스베가스': 1.5,
'넘버3': 5.0,
'세계대전': 3.0,
'사랑과전쟁': 3.5,
},
'소녀시대': {
'택시운전사': 2.5,
'겨울왕국': 3.0,
'넘버3': 3.5,
'세계대전': 4.0,
},
'마마무': {
'겨울왕국': 3.5,
'리빙라스베가스': 3.0,
'세계대전': 4.5,
'넘버3': 4.0,
'사랑과전쟁': 2.5,
},
'오마이걸': {
'택시운전사': 3.0,
'겨울왕국': 4.0,
'리빙라스베가스': 2.0,
'넘버3': 3.0,
'세계대전': 3.5,
'사랑과전쟁': 2.0,
},
'모모랜드': {
'택시운전사': 3.0,
'겨울왕국': 4.0,
'세계대전': 3.0,
'넘버3': 5.0,
'사랑과전쟁': 3.5,
},
'우주소녀': {'겨울왕국': 4.5, '사랑과전쟁': 1.0, '넘버3': 4.0},
}

In [55]:
df=pd.DataFrame(critics)
df

         레드벨벳  BTS  블랙핑크  소녀시대  마마무  오마이걸  모모랜드  우주소녀
택시운전사     2.5  1.0   3.0   2.5  NaN   3.0   3.0   NaN
겨울왕국      3.5  4.5   3.5   3.0  3.5   4.0   4.0   4.5
리빙라스베가스   3.0  0.5   1.5   NaN  3.0   2.0   NaN   NaN
넘버3       3.5  1.5   5.0   3.5  4.0   3.0   5.0   4.0
사랑과전쟁     2.5  4.5   3.5   NaN  2.5   2.0   3.5   1.0
세계대전      3.0  5.0   3.0   4.0  4.5   3.5   3.0   NaN

In [56]:
grade1 = []
grade2 = []
sum_team1 = 0
sum_team2 = 0
sum_pow1 = 0
sum_pow2 = 0
sum1 = 0
sum2 = 0

def similarity_team(date,team1,team2):
    grade1 = []
    grade2 = []
    sum_team1 = 0
    sum_team2 = 0
    sum_pow1 = 0
    sum_pow2 = 0
    sum1 = 0
    sum2 = 0
    sum_grade = 0
    for movie in critics[team1]:
        if movie in critics[team2]:
            grade1.append(critics[team1][movie])
            grade2.append(critics[team2][movie])

    for i in grade1:
        sum_team1 += i
    for i in grade2:
        sum_team2 += i
    for i in grade1:
        sum_pow1 += pow(i,2)
    for i in grade2:
        sum_pow2 += pow(i,2)
    for i in range(0,len(grade1)):
        a = grade1[i]*grade2[i]
        sum_grade += a

    lenth=len(grade1)
    res1 = sum_grade-(sum1*sum2/lenth)
    res2 = sqrt((sum_pow1-pow(sum1,2)/lenth)*(sum_pow2-(pow(sum2,2)/lenth)))
    result = res1/res2
    
    return result

In [57]:
print(similarity_team(critics,'우주소녀','레드벨벳'))
print(similarity_team(critics,'우주소녀','BTS'))
print(similarity_team(critics,'우주소녀','블랙핑크'))
print(similarity_team(critics,'우주소녀','소녀시대'))
print(similarity_team(critics,'우주소녀','마마무'))
print(similarity_team(critics,'우주소녀','오마이걸'))
print(similarity_team(critics,'우주소녀','모모랜드'))
print(similarity_team(critics,'우주소녀','우주소녀'))

0.9528927449621697
0.7705732382498681
0.9140583557872861
0.9908301680442989
0.9554058358905754
0.973616310567801
0.931805248032154
1.0

In [58]:
우주소녀 그룹과 가장 유사한 그룹은 소녀시대 이며, 소녀시대가 가장높은 평점을 준 세계대전을 
우주소녀에게 추천합니다.

SyntaxError: invalid syntax (<ipython-input-58-c554c6e2cd92>, line 1)